# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# CDS Books is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  chrome: stable # https://docs.travis-ci.com/user/chrome
  postgresql: "9.6"

notifications:
  email: # sent to the committer and the author
    on_success: never # default: always
    on_failure: always # default: always

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - postgresql
  - redis
  - rabbitmq

env:
  global:
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
    - PIPENV_PYUP_API_KEY=""

python:
  - "3.6"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES7_DOWNLOAD_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "nvm install 12; nvm use 12"
  - "travis_retry pip install --upgrade pip setuptools py pipenv"
  - "travis_retry pip install twine wheel coveralls"

install:
  - "./scripts/bootstrap"

script:
  - ./run-tests.sh

after_success:
  - coveralls
